#!/usr/bin/env python3
"""Rollback app/staging domains using a saved checkpoint snapshot."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class RollbackConfig:
    snapshot_path: Path
    apply: bool


class DomainRollback:
    def __init__(self, config: RollbackConfig) -> None:
        self.config = config

    @staticmethod
    def parse_args() -> RollbackConfig:
        parser = argparse.ArgumentParser(
            description="Rollback app/staging aliases from a checkpoint snapshot."
        )
        parser.add_argument(
            "--snapshot",
            required=True,
            help="Path to checkpoint JSON generated by scripts/create_checkpoint.py",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Execute alias changes. Default is dry-run.",
        )
        args = parser.parse_args()
        return RollbackConfig(snapshot_path=Path(args.snapshot).resolve(), apply=args.apply)

    def run(self) -> int:
        self._require_command("vercel")
        snapshot = self._load_snapshot()

        app = snapshot["vercel"]["app_domain"]
        staging = snapshot["vercel"]["staging_domain"]

        app_url = app["deployment_url"]
        app_domain = app["domain"]
        staging_url = staging["deployment_url"]
        staging_domain = staging["domain"]
        if not app_url or not staging_url:
            raise RuntimeError("Snapshot does not include deployment URLs for app/staging.")

        commands = [
            ["vercel", "alias", "set", app_url, app_domain],
            ["vercel", "alias", "set", staging_url, staging_domain],
        ]

        print("Rollback plan:")
        print(f"- {app_domain} -> {app_url}")
        print(f"- {staging_domain} -> {staging_url}")

        if not self.config.apply:
            print("Dry-run mode. Run with --apply to execute.")
            return 0

        for command in commands:
            subprocess.run(command, check=True, text=True, capture_output=False)
        print("Rollback aliases applied successfully.")
        return 0

    def _load_snapshot(self) -> dict:
        if not self.config.snapshot_path.exists():
            raise RuntimeError(f"Snapshot file not found: {self.config.snapshot_path}")
        return json.loads(self.config.snapshot_path.read_text(encoding="utf-8"))

    @staticmethod
    def _require_command(command: str) -> None:
        if shutil.which(command):
            return
        raise RuntimeError(f"Required command not found: {command}")


def main() -> int:
    try:
        config = DomainRollback.parse_args()
        return DomainRollback(config).run()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
